### ISSUE TITLE
Feature: Support outline icons

### ISSUE THREAD

**Issue by abennouna** [GerritErpenstein/ionic2-custom-icons#9]
Do you think it would be easy to add support for outline stroke icons? It would be a nice to have for iOS.

**Comment by GerritErpenstein** [comment]
Sounds like a reasonable feature. Let's see if I come up with a good idea...

**Comment by GerritErpenstein** [comment]
If all is going well, I will release a new version with the requested feature in the next few days.

**Comment by GerritErpenstein** [comment]
See https://github.com/GerritErpenstein/ionic2-custom-icons-example/tree/feature/platform-specific for an example of the (yet unstable) release of the feature.
Please let me know if you have any suggestions. The docs haven't been updated yet but I think it's pretty self-explaining how it works.

**Comment by mavogel** [comment]
@GerritErpenstein thx for this nice feature. Added it to my app and it works great (for tabs as well). It's nice with the (ion|md) suffix. At first I expected (ion|md) as prefix, like ionic internally does, but it's better your way, cuz then the icon are also sorted in my folder on the disc.

Took me a while to find out you changed the path `config/sass.config.js` 
```js
from: 'node_modules/ionic2-custom-icons/directive/scss/',
to: 'node_modules/ionic2-custom-icons/ionic/scss/',
```
but as you said: docs weren't updated yet from `0.3.x` to `0.4.x`.

One **suggestion** would be to be able to scale the custom icons of the tabs. They are really tiny, especially if I remove the text below the icon. Or is this possible with ionic2 out of the box?

**Comment by GerritErpenstein** [comment]
Hi @mavogel! Thanks for the kind feedback. I am still working on this feature. The next (beta) release will support inactive ("outline" for iOS) icons. After finishing that, I will update and rewrite the docs. Until then the feature branch in the ionic2-custom-icons-example contains a working example with the new features.

> One suggestion would be to be able to scale the custom icons of the tabs. They are really tiny, especially if I remove the text below the icon. Or is this possible with ionic2 out of the box?

I will look into it. Ideally the size should be as close to the size of the original Ionic icon set as possible.

**Comment by GerritErpenstein** [comment]
I have just push a commit that should make the next release feature complete. Inactive ("outline") icons are fully supported now. The example app (in the platform-specific branch) has also been updated.
The next step is to update the docs and make a stable release.

Feel free to test the update and please let me know if you find any problems. Thanks!

**Comment by mavogel** [comment]
@GerritErpenstein thank for th update. Outline icons work fine for me now.
For me the tab icons are still really small for iOS. (or maybe it's meant to be this small by ios conventions. I'm new to app dev...) 
It tried it with your `platform-logo`. I also saw that it's possible to pass a `small` parameter to the `<custom-icon>` and probably something like `large`. Is this also possible in a way for tabs?

**Comment by GerritErpenstein** [comment]
@mavogel 
The small icons issue for tabs should be fixed in `ionic2-custom-icons 0.4.1-beta.3`. Thanks for your feedback!

**Comment by sarahsga** [comment]
@GerritErpenstein my custom outline icons still appear with the fill, I tried the heart icon, the outline works for that, but for some icons, it does not. Try the svg I've attached (inside the .zip because .svg was not allowed)
[devices.svg.zip](https://github.com/GerritErpenstein/ionic2-custom-icons/files/986705/devices.svg.zip)

**Comment by GerritErpenstein** [comment]
@sarahsga I have taken a look into your SVG. Please try to remove all SVG transforms. They have caused problems in the past.
Attached you can find an edited version of your SVG that works with this library
[devices_edited.zip](https://github.com/GerritErpenstein/ionic2-custom-icons/files/998438/devices_edited.zip)
.
